#!/bin/bash

set -e

if (($# != 1)); then
	echo "Usage: $0 <input file name>"
	exit 1
fi

directory=$(dirname $1)
filename=$(basename $1)
basename="${filename%.*}"

./instant --jasmin "$basename" < "$1" > "$directory/$basename.j"
java -jar lib/jasmin.jar -d "$directory" "$directory/$basename.j" 1>/dev/null
